name: Build and Publish

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPOSITORY: 'komoju/debug'
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

permissions:
  packages: write # GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            platform: linux/amd64
          - target: aarch64-unknown-linux-gnu
            platform: linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: ${{ github.ref == 'refs/heads/main' && 'type=gha,mode=max' || '' }}
          load: true
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          provenance: false
          tags: ghcr.io/${{ env.REPOSITORY }}
          labels: |
            com.datadoghq.tags.version=${{ env.SHA }},
            com.datadoghq.tags.service=debug,
            com.datadoghq.tags.team=sre

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.target }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  publish:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs:
      - build

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: >
          docker buildx imagetools create
          -t ghcr.io/${{ env.REPOSITORY }}:latest
          -t ghcr.io/${{ env.REPOSITORY }}:${{ env.SHA }}
          $(printf 'ghcr.io/${{ env.REPOSITORY }}@sha256:%s ' *)
